[package]
name = "day07"
version = "0.1.0"
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
edition = "2021"

[dependencies]
aoc-common = { path = "../aoc-common" }
itertools = "0.13.0"
tracing = "0.1.41"

[dev-dependencies]
rstest = "0.23.0"
